Repository zellij-org/zellij, pull requests merged in 2022-10, with the labels that each got.

#1761 flake.lock: Update
  flake.lock
Labels: dependencies, nix

#1775 zellij-server: improve thread_bus error handling
  zellij-server/src/screen.rs
  zellij-server/src/tab/mod.rs
  zellij-server/src/thread_bus.rs
  zellij-utils/src/errors.rs
Labels: hacktoberfest-accepted

#1808 improve error handling in route
  zellij-server/src/lib.rs
  zellij-server/src/route.rs
  zellij-server/src/unit/screen_tests.rs
Labels: hacktoberfest-accepted

#1834 rust-toolchain: Update
  rust-toolchain.toml
Labels: dependencies, automated, rust
